### ISSUE TITLE
make colours consistent across the charts

### ISSUE THREAD

**Issue by InigoP** [FlowWest/sdg-dashboard#13]
ensure that the same parameter is the same color in the entire dashboard

**Comment by MaddeeRubenson** [comment]
updates to visuals reflected here: https://github.com/FlowWest/sdg-dashboard/blob/visual-updates/visualization_exploration.ipynb

**Comment by ergz** [comment]
can you paste a couple of the plots that show this, github doesn't show diffs very well for notebooks

**Comment by MaddeeRubenson** [comment]
![Image](https://github.com/user-attachments/assets/2dd0ce5e-1d03-4e21-86a8-866995bb512d)
![Image](https://github.com/user-attachments/assets/dda4ea79-cec6-4211-82ce-eba0275de25b)

**Comment by ergz** [comment]
looks great! @InigoP we need to integrate these versions into the streamlit app
